# Generated by Django 3.1 on 2021-06-27 19:25

from django.db import migrations, models
import filer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expire_on', models.DateTimeField()),
                ('myfile', models.FileField(upload_to=filer.models.get_file_path)),
            ],
        ),
    ]
