name: Django CI

on:
  push:
    branches: [ main, naman-new ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  publish:
    runs-on: [ self-hosted ]
    needs: [build]
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install MySQL libraries
      run: sudo apt-get install python3-dev default-libmysqlclient-dev build-essential -y

    - name: Create Virtualenv and Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install virtualenv
        python -m virtualenv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

    - name: Run deploy script
      run: |
        sh ./deploy.sh
